### ISSUE TITLE
[FEATURE] Use more of Notifications API

### ISSUE THREAD

**Issue by Wamy-Dev** [mohamedfakhreldin/AUD-Notifier#2]
This is a pretty good library, and makes the notifications API easy to use. It is missing some things though.

- Adding images to notifications.
- Adding messages or descriptions under the title to notifications.

Would be nice if this library had some of those. Keep up the good work!

**Comment by mohamedfakhreldin** [comment]
This library also supports  adding images and descriptions, unless the browser doesn't support it

Thanks

**Comment by Wamy-Dev** [comment]
What are the options for this?

**Comment by mohamedfakhreldin** [comment]
native options body, icon and image
